/*
 * generated by Xtext 2.15.0
 */
package trabalho3


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class ReceitaHTMLStandaloneSetup extends ReceitaHTMLStandaloneSetupGenerated {

	def static void doSetup() {
		new ReceitaHTMLStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
